export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_ONE_ITEM = 'FETCH_ONE_ITEM';
export const FETCH_ONE_ITEM_SUCCESS = 'FETCH_ONE_ITEM_SUCCESS';
export const FETCH_ONE_ITEM_FAILURE = 'FETCH_ONE_ITEM_FAILURE';

export const CREATE_ITEM = 'CREATE_ITEM';
export const CREATE_ITEM_SUCCESS = 'CREATE_ITEM_SUCCESS';
export const CREATE_ITEM_FAILURE = 'CREATE_ITEM_FAILURE';
